package gr.soule.mavenbook.springwebpp.article;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2015.04.19 at 11:24:56 PM EEST 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;simpleContent>
*     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
*       &lt;attribute name="term" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
*     &lt;/extension>
*   &lt;/simpleContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "value"
})
@XmlRootElement(name = "category")
public class Category {

 @XmlValue
 protected String value;
 @XmlAttribute
 protected String term;
 @XmlAttribute
 protected String label;

 /**
  * Gets the value of the value property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getValue() {
     return value;
 }

 /**
  * Sets the value of the value property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setValue(String value) {
     this.value = value;
 }

 /**
  * Gets the value of the term property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getTerm() {
     return term;
 }

 /**
  * Sets the value of the term property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setTerm(String value) {
     this.term = value;
 }

 /**
  * Gets the value of the label property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getLabel() {
     return label;
 }

 /**
  * Sets the value of the label property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setLabel(String value) {
     this.label = value;
 }

}

