package gr.soule.mavenbook.springwebpp.article;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2015.04.19 at 11:24:56 PM EEST 
//



import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element ref="{http://www.w3.org/2005/Atom}type"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}title"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}link" maxOccurs="unbounded" minOccurs="0"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}category" maxOccurs="unbounded" minOccurs="0"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}author"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}id"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}updated"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}published"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}summary"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "type",
 "title",
 "link",
 "category",
 "author",
 "id",
 "updated",
 "published",
 "summary"
})
@XmlRootElement(name = "entry")
public class Entry {

 @XmlElement(required = true)
 protected String type;
 @XmlElement(required = true)
 protected String title;
 protected List<Link> link;
 protected List<Category> category;
 @XmlElement(required = true)
 protected Author author;
 @XmlElement(required = true)
 protected String id;
 @XmlElement(required = true)
 protected String updated;
 @XmlElement(required = true)
 protected String published;
 @XmlElement(required = true)
 protected String summary;

 /**
  * Gets the value of the type property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getType() {
     return type;
 }

 /**
  * Sets the value of the type property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setType(String value) {
     this.type = value;
 }

 /**
  * Gets the value of the title property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getTitle() {
     return title;
 }

 /**
  * Sets the value of the title property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setTitle(String value) {
     this.title = value;
 }

 /**
  * Gets the value of the link property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the link property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getLink().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link Link }
  * 
  * 
  */
 public List<Link> getLink() {
     if (link == null) {
         link = new ArrayList<Link>();
     }
     return this.link;
 }

 /**
  * Gets the value of the category property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the category property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getCategory().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link Category }
  * 
  * 
  */
 public List<Category> getCategory() {
     if (category == null) {
         category = new ArrayList<Category>();
     }
     return this.category;
 }

 /**
  * Gets the value of the author property.
  * 
  * @return
  *     possible object is
  *     {@link Author }
  *     
  */
 public Author getAuthor() {
     return author;
 }

 /**
  * Sets the value of the author property.
  * 
  * @param value
  *     allowed object is
  *     {@link Author }
  *     
  */
 public void setAuthor(Author value) {
     this.author = value;
 }

 /**
  * Gets the value of the id property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getId() {
     return id;
 }

 /**
  * Sets the value of the id property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setId(String value) {
     this.id = value;
 }

 /**
  * Gets the value of the updated property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getUpdated() {
     return updated;
 }

 /**
  * Sets the value of the updated property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setUpdated(String value) {
     this.updated = value;
 }

 /**
  * Gets the value of the published property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getPublished() {
     return published;
 }

 /**
  * Sets the value of the published property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setPublished(String value) {
     this.published = value;
 }

 /**
  * Gets the value of the summary property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getSummary() {
     return summary;
 }

 /**
  * Sets the value of the summary property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setSummary(String value) {
     this.summary = value;
 }

}
