package gr.soule.mavenbook.springwebpp.article;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2015.04.19 at 11:24:56 PM EEST 
//



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element ref="{http://www.w3.org/2005/Atom}title"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}link"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}subtitle"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}updated"/>
*         &lt;element ref="{http://www.w3.org/2005/Atom}entry"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "title",
 "link",
 "subtitle",
 "updated",
 "entry"
})
@XmlRootElement(name = "feed")
public class Feed {

 @XmlElement(required = true)
 protected String title;
 @XmlElement(required = true)
 protected Link link;
 @XmlElement(required = true)
 protected String subtitle;
 @XmlElement(required = true)
 protected String updated;
 @XmlElement(required = true)
 protected Entry entry;

 /**
  * Gets the value of the title property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getTitle() {
     return title;
 }

 /**
  * Sets the value of the title property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setTitle(String value) {
     this.title = value;
 }

 /**
  * Gets the value of the link property.
  * 
  * @return
  *     possible object is
  *     {@link Link }
  *     
  */
 public Link getLink() {
     return link;
 }

 /**
  * Sets the value of the link property.
  * 
  * @param value
  *     allowed object is
  *     {@link Link }
  *     
  */
 public void setLink(Link value) {
     this.link = value;
 }

 /**
  * Gets the value of the subtitle property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getSubtitle() {
     return subtitle;
 }

 /**
  * Sets the value of the subtitle property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setSubtitle(String value) {
     this.subtitle = value;
 }

 /**
  * Gets the value of the updated property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getUpdated() {
     return updated;
 }

 /**
  * Sets the value of the updated property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setUpdated(String value) {
     this.updated = value;
 }

 /**
  * Gets the value of the entry property.
  * 
  * @return
  *     possible object is
  *     {@link Entry }
  *     
  */
 public Entry getEntry() {
     return entry;
 }

 /**
  * Sets the value of the entry property.
  * 
  * @param value
  *     allowed object is
  *     {@link Entry }
  *     
  */
 public void setEntry(Entry value) {
     this.entry = value;
 }

}
