package gr.soule.mavenbook.springwebpp.article;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2015.04.19 at 11:24:56 PM EEST 
//



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;simpleContent>
*     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
*       &lt;attribute name="rel" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="credits" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" />
*       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
*     &lt;/extension>
*   &lt;/simpleContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "value"
})
@XmlRootElement(name = "link")
public class Link {

 @XmlValue
 protected String value;
 @XmlAttribute
 protected String rel;
 @XmlAttribute
 protected String href;
 @XmlAttribute
 protected String comment;
 @XmlAttribute
 protected String type;
 @XmlAttribute
 protected String title;
 @XmlAttribute
 protected String credits;
 @XmlAttribute
 protected String caption;
 @XmlAttribute
 protected String code;

 /**
  * Gets the value of the value property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getValue() {
     return value;
 }

 /**
  * Sets the value of the value property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setValue(String value) {
     this.value = value;
 }

 /**
  * Gets the value of the rel property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getRel() {
     return rel;
 }

 /**
  * Sets the value of the rel property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setRel(String value) {
     this.rel = value;
 }

 /**
  * Gets the value of the href property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getHref() {
     return href;
 }

 /**
  * Sets the value of the href property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setHref(String value) {
     this.href = value;
 }

 /**
  * Gets the value of the comment property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getComment() {
     return comment;
 }

 /**
  * Sets the value of the comment property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setComment(String value) {
     this.comment = value;
 }

 /**
  * Gets the value of the type property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getType() {
     return type;
 }

 /**
  * Sets the value of the type property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setType(String value) {
     this.type = value;
 }

 /**
  * Gets the value of the title property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getTitle() {
     return title;
 }

 /**
  * Sets the value of the title property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setTitle(String value) {
     this.title = value;
 }

 /**
  * Gets the value of the credits property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getCredits() {
     return credits;
 }

 /**
  * Sets the value of the credits property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setCredits(String value) {
     this.credits = value;
 }

 /**
  * Gets the value of the caption property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getCaption() {
     return caption;
 }

 /**
  * Sets the value of the caption property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setCaption(String value) {
     this.caption = value;
 }

 /**
  * Gets the value of the code property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getCode() {
     return code;
 }

 /**
  * Sets the value of the code property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setCode(String value) {
     this.code = value;
 }

}
