package gr.soule.mavenbook.springwebpp.article;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2015.04.19 at 11:24:56 PM EEST 
//



import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
* This object contains factory methods for each 
* Java content interface and Java element interface 
* generated in the gr.soule.mavenbook.atricle package. 
* <p>An ObjectFactory allows you to programatically 
* construct new instances of the Java representation 
* for XML content. The Java representation of XML 
* content can consist of schema derived interfaces 
* and classes representing the binding of schema 
* type definitions, element declarations and model 
* groups.  Factory methods for each of these are 
* provided in this class.
* 
*/
@XmlRegistry
public class ObjectFactory {

 private final static QName _Title_QNAME = new QName("http://www.w3.org/2005/Atom", "title");
 private final static QName _Id_QNAME = new QName("http://www.w3.org/2005/Atom", "id");
 private final static QName _Summary_QNAME = new QName("http://www.w3.org/2005/Atom", "summary");
 private final static QName _Name_QNAME = new QName("http://www.w3.org/2005/Atom", "name");
 private final static QName _Updated_QNAME = new QName("http://www.w3.org/2005/Atom", "updated");
 private final static QName _Subtitle_QNAME = new QName("http://www.w3.org/2005/Atom", "subtitle");
 private final static QName _Published_QNAME = new QName("http://www.w3.org/2005/Atom", "published");
 private final static QName _Type_QNAME = new QName("http://www.w3.org/2005/Atom", "type");

 /**
  * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gr.soule.mavenbook.atricle
  * 
  */
 public ObjectFactory() {
 }

 /**
  * Create an instance of {@link Link }
  * 
  */
 public Link createLink() {
     return new Link();
 }

 /**
  * Create an instance of {@link Category }
  * 
  */
 public Category createCategory() {
     return new Category();
 }

 /**
  * Create an instance of {@link Feed }
  * 
  */
 public Feed createFeed() {
     return new Feed();
 }

 /**
  * Create an instance of {@link Entry }
  * 
  */
 public Entry createEntry() {
     return new Entry();
 }

 /**
  * Create an instance of {@link Author }
  * 
  */
 public Author createAuthor() {
     return new Author();
 }

 /**
  * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
  * 
  */
 @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "title")
 public JAXBElement<String> createTitle(String value) {
     return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
 }

 /**
  * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
  * 
  */
 @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "id")
 public JAXBElement<String> createId(String value) {
     return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
 }

 /**
  * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
  * 
  */
 @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "summary")
 public JAXBElement<String> createSummary(String value) {
     return new JAXBElement<String>(_Summary_QNAME, String.class, null, value);
 }

 /**
  * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
  * 
  */
 @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "name")
 public JAXBElement<String> createName(String value) {
     return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
 }

 /**
  * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
  * 
  */
 @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "updated")
 public JAXBElement<String> createUpdated(String value) {
     return new JAXBElement<String>(_Updated_QNAME, String.class, null, value);
 }

 /**
  * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
  * 
  */
 @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "subtitle")
 public JAXBElement<String> createSubtitle(String value) {
     return new JAXBElement<String>(_Subtitle_QNAME, String.class, null, value);
 }

 /**
  * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
  * 
  */
 @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "published")
 public JAXBElement<String> createPublished(String value) {
     return new JAXBElement<String>(_Published_QNAME, String.class, null, value);
 }

 /**
  * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
  * 
  */
 @XmlElementDecl(namespace = "http://www.w3.org/2005/Atom", name = "type")
 public JAXBElement<String> createType(String value) {
     return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
 }

}

